spring.application.name=HangmanSpringBoot
server.port=8080
spring.thymeleaf.cache=false
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
logging.level.ph.edu.dlsu.lbycpob.hangman=DEBUG